name: Build and Deploy Vehicle Rental app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Vehicle Rental app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run:  mvn -B package --file pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/Advanced-Vehicle-Rental-Mananagement-System:$(date +'%Y-%m-%d%H-%M-%S')
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/Advanced-Vehicle-Rental-Mananagement-System:$(date-'%Y-%m-%d%H-%M-%S')