name: Build and Deploy Vehicle Rental app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Vehicle Rental app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          nvm clean
          mvn -B package --file pom.xml