name: Build and Deploy Vehicle Rental app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Vehicle Rental app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: mvn -B package --file pom.xml

      - name: Generate timestamp
        id: vars
        run: echo "timestamp=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/advanced-vehicle-rental-management-system:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/advanced-vehicle-rental-management-system:${{ steps.vars.outputs.timestamp }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/advanced-vehicle-rental-management-system:${{ github.sha }}
